spring:
  application:
    name: Haebollangce_v2.0
  # jpa
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  # 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/haebollangce
    username: root
    password: Root123
    driver-class-name: org.mariadb.jdbc.Driver
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  